-- ==============================================================================
-- Migration: Switch all embeddings from OpenAI (1536-dim) to ColQwen2 (128-dim)
-- ==============================================================================
-- This migration changes all vector columns from VECTOR(1536) to VECTOR(128).
-- Existing embeddings are dropped and must be regenerated by reprocessing
-- documents and re-indexing schema catalogs.
-- ==============================================================================

-- 1. Document chunks: drop old index, alter column, recreate index
DROP INDEX IF EXISTS document_chunks_embedding_idx;
ALTER TABLE document_chunks DROP COLUMN IF EXISTS embedding;
ALTER TABLE document_chunks ADD COLUMN embedding VECTOR(128);
CREATE INDEX IF NOT EXISTS document_chunks_embedding_idx
    ON document_chunks USING vchordrq (embedding vector_cosine_ops);

-- 2. Schema definitions: drop old index, alter column, recreate index
DROP INDEX IF EXISTS idx_schema_definitions_vector;
ALTER TABLE schema_definitions DROP COLUMN IF EXISTS embedding;
ALTER TABLE schema_definitions ADD COLUMN embedding VECTOR(128);
CREATE INDEX IF NOT EXISTS idx_schema_definitions_vector
    ON schema_definitions USING vchordrq (embedding vector_cosine_ops);

-- NOTE: document_pages.visual_embedding is already VECTOR(128) — no change needed.
-- NOTE: After running this migration, you must:
--   1. Reprocess all documents (re-upload or trigger reprocessing)
--   2. Re-index all schema catalogs (connectors)
